% dataCapytaine loads and visualizes hydrodynamic data generated by the
% MSS-Capytaine Python add-on. MSS-Capytaine uses Capytaine to compute the
% hydrodynamic coefficients and RAOs, and exports the results as an MSS vessel
% structure for further analysis in MATLAB/Octave.
%
% Before running this script, add the Marine Systems Simulator (MSS) folders to 
% the MATLAB path using mssPath.m and check that you have the two MSS-Capytaine 
% data files located under .../MSS/HYDRO/vessels_capytaine/capytaineTestShip/
% 
%   capytaineTestShip.mat - Hydrodynamic data stored in the MSS structure vessel
%   generated_hull_panels.mat - Generated hull mesh data file
% 
% You can regenerate the MSS data files in MSS-Capytaine by running the
% command "python main.py" from the MSS-Capytaine project directory.
%
% Generated input files:
%   load(capytaineTestShip)       - Load MSS 'vessel' structure
%   load(generated_hull_panels)   - load hull vertices and panel connectivity
%
% MSS dependencies:
%   computeManeuveringModel.m     - computes the zero-speed maneuvering model
%   vesselPeriods.m               - computes natural periods and damping ratios
%   plotTF.m                      - plots force response amplitude operators
%   plotABC.m                     - plots added mass and damping matrices
%   plotBv.m                      - plots viscous damping
%
% Author: Thor I. Fossen
% Date: 2026-09-23
% Revisions:

%% Load results generated by the Python add-on
results_dir = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
    'capytaineTestShip', 'results');
load(fullfile(results_dir, 'capytaineTestShip.mat'));
load(fullfile(results_dir, 'generated_hull_panels.mat'));

%% Compute the MSS maneuvering model and vessel periods
omega_p = 0.8;
vessel = computeManeuveringModel(vessel, omega_p, ...
    vessel.powerBased.kappa_126, ...    % Specified in config.json 
    vessel.powerBased.delta_zeta_345);  % Specified in config.json 

% vesselPeriods expects frequency-indexed A and B matrices.
Aw = vessel.A(:,:,:,1);
Bw = vessel.B(:,:,:,1) + vessel.powerBased.Bv;

[T,zeta,omega,omega_n] = vesselPeriods( ...
    vessel.freqs, vessel.MRB, Aw, Bw, vessel.G, 'coupled', true);

%% Display data
display(vessel.M,'M')
display(vessel.D,'D')
display(vessel.G,'G')

%% Plot the generated hull-panel mesh
figure(gcf)
patch('Vertices', vertices, ...
    'Faces', faces, ...
    'FaceColor', [0.8 0.8 0.8], ...
    'EdgeColor', 'k');

axis equal
grid on
xlabel('x [m]')
ylabel('y [m]')
zlabel('z [m]')
view(3)

%% Plot the MSS hydrodynamic data
plotTF(vessel,'force','rads')
plotABC(vessel,'A')
plotABC(vessel,'B')
plotBv(vessel)
