function vessel = plotLAUV_marie()
% plotLAUV_marie loads and visualizes hydrodynamic data generated by the
% MSS-Capytaine Python add-on. MSS-Capytaine uses Capytaine to compute the
% hydrodynamic coefficients and RAOs, and exports the results as an MSS vessel
% structure for further analysis in MATLAB/Octave.
%
% Before running this function, add the Marine Systems Simulator (MSS) folders
% to the MATLAB path using mssPath.m and check that you have the two
% MSS-Capytaine data files under
% .../MSS-Capytaine/vessels_capytaine/LAUV_marie/results/
%
%   LAUV_marie.mat             - Hydrodynamic data in the MSS vessel structure
%   generated_hull_panels.mat  - Generated hull mesh data
%
% You can regenerate these files from the MSS-Capytaine project directory with:
%
%   python main.py LAUV_marie
%
% Generated input files:
%   load(LAUV_marie)            - Load MSS 'vessel' structure
%   load(generated_hull_panels) - Load hull vertices and panel connectivity
%
% MSS dependencies:
%   computeManeuveringModel.m   - Computes the power-based maneuvering model
%   plotTF.m                    - Plots force response amplitude operators
%   plotABC.m                   - Plots added mass and damping matrices
%   plotBv.m                    - Plots viscous damping
%
% The fully submerged LAUV has no hydrostatic heave stiffness. Consequently,
% vesselPeriods.m, which evaluates the heave, roll, and pitch modes of a
% positively restored vessel, is not called by this example.
%
% Usage:
%   plotLAUV_marie
%   vessel = plotLAUV_marie();
%
% Author: Thor I. Fossen
% Date: 2026-10-04
% Revisions: 

%% Load results generated by the Python add-on
results_dir = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
    'vessels_capytaine', 'LAUV_marie', 'results');
load(fullfile(results_dir, 'LAUV_marie.mat'));
load(fullfile(results_dir, 'generated_hull_panels.mat'));

%% Compute the MSS maneuvering model
omega_p = 0.8;
% Reuse T_1236 and delta_zeta_45 exported from config.json.
vessel = computeManeuveringModel(vessel, omega_p);

%% Display data
display(vessel.M, 'M')
display(vessel.D, 'D')
display(vessel.G, 'G')

%% Plot the generated hull-panel mesh
plotPanelMesh(vertices, faces, 'LAUV Marie hull-panel mesh', ...
    'MSSCapytaineLAUVMesh');

%% Plot the MSS hydrodynamic data
plotTF(vessel, 'force', 'rads')
plotABC(vessel, 'A')
plotABC(vessel, 'B')
plotBv(vessel)

end

function plotPanelMesh(vertices, faces, figure_name, figure_tag)
% Plot triangular faces and their edges without degenerate patch edges.

% Capytaine represents every triangle as a four-index face with the final
% vertex repeated. MATLAB can render those degenerate patch edges as long
% rays. Validate the indices and retain the three unique triangle vertices.
triangles = double(faces(:, 1:3));
number_of_vertices = size(vertices, 1);

if any(~isfinite(triangles(:))) || ...
        any(triangles(:) ~= fix(triangles(:))) || ...
        any(triangles(:) < 1) || ...
        any(triangles(:) > number_of_vertices)
    error('Hull-panel faces contain invalid MATLAB vertex indices.');
end

% Use a case-specific figure so plotting LAUV Marie does not clear the
% testShip mesh. Reuse only a previous figure from this same case.
mesh_figure = findobj(0, 'Type', 'figure', 'Tag', figure_tag);
if isempty(mesh_figure)
    mesh_figure = figure('Name', figure_name, ...
        'NumberTitle', 'off', 'Tag', figure_tag);
else
    mesh_figure = mesh_figure(1);
    clf(mesh_figure)
    figure(mesh_figure)
end
mesh_axes = axes('Parent', mesh_figure);

% Draw the filled surface without patch edges, then draw the unique edges
% explicitly. This avoids the MATLAB patch artifact at closed end caps.
trisurf(triangles, vertices(:, 1), vertices(:, 2), vertices(:, 3), ...
    'Parent', mesh_axes, ...
    'FaceColor', [0.8 0.8 0.8], ...
    'EdgeColor', 'none');

mesh_edges = [triangles(:, [1 2]); ...
              triangles(:, [2 3]); ...
              triangles(:, [3 1])];
mesh_edges = unique(sort(mesh_edges, 2), 'rows');
number_of_edges = size(mesh_edges, 1);

edge_x = [vertices(mesh_edges(:, 1), 1), ...
          vertices(mesh_edges(:, 2), 1), nan(number_of_edges, 1)]';
edge_y = [vertices(mesh_edges(:, 1), 2), ...
          vertices(mesh_edges(:, 2), 2), nan(number_of_edges, 1)]';
edge_z = [vertices(mesh_edges(:, 1), 3), ...
          vertices(mesh_edges(:, 2), 3), nan(number_of_edges, 1)]';

hold(mesh_axes, 'on')
plot3(mesh_axes, edge_x(:), edge_y(:), edge_z(:), 'k-', ...
    'LineWidth', 0.5)
hold(mesh_axes, 'off')

axis(mesh_axes, 'equal')
grid(mesh_axes, 'on')
xlabel(mesh_axes, 'x [m]')
ylabel(mesh_axes, 'y [m]')
zlabel(mesh_axes, 'z [m]')
view(mesh_axes, 3)
end
